version: "3.9"
services:
  db-stock:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_DB=stock
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=test1234
    ports:
      - 5434:5432
    volumes:
      - stock-pg-data:/var/lib/postgresql/data
volumes:
  stock-pg-data: